docsis_version: "3.1"
tlvs:
  - type: 3
    name: "Network Access Control"
    length: 1
    formatted_value: 1
    description: "Web access enabled/disabled"
    value_type: boolean
  - type: 24
    length: 7
    formatted_value: "Compound TLV with 2 sub-TLVs"
    value_type: compound
    subtlvs:
      - type: 1
        name: "Downstream Frequency"
        length: 2
        formatted_value: 1
        description: "Frequency in Hz"
      - type: 6
        name: "TFTP Server"
        length: 1
        formatted_value: 7
        description: "TFTP server MAC address"
  - type: 25
    length: 7
    formatted_value: "Compound TLV with 2 sub-TLVs"
    value_type: compound
    subtlvs:
      - type: 1
        name: "Downstream Frequency"
        length: 2
        formatted_value: 2
        description: "Frequency in Hz"
      - type: 6
        name: "TFTP Server"
        length: 1
        formatted_value: 7
        description: "TFTP server MAC address"
  - type: 6
    name: "TFTP Server"
    length: 16
    formatted_value: "1A 3B A2 E7 66 62 90 B9 72 56 05 71 8C 01 F9 67"
    description: "TFTP server MAC address"
    value_type: binary
  - type: 7
    name: "Software Upgrade Server"
    length: 16
    formatted_value: "CB 5B 00 55 AA D7 91 03 51 96 91 CC A2 CB BE 0F"
    description: "Server MAC address"
    value_type: binary