defmodule Bindocsis.Generators.ConfigGenerator do
  @moduledoc """
  Generates the human-readable config format from TLVs.

  Names come from `Bindocsis.ConfigNames` (derived from the spec tables,
  issue #6) and values from `Bindocsis.ValueFormatter`, so the text is the
  same human form used for `formatted_value` in JSON/YAML:

      # DOCSIS Configuration File
      # Generated by Bindocsis

      NetworkAccessControl Enabled
      DownstreamFrequency 591 MHz
      UpstreamServiceFlow {
          ServiceFlowReference 1
          QoSParameterSetType Provisioned+Admitted+Active (7)
      }
      TLV254 AA BB

  Every leaf is checked to round-trip through `Bindocsis.ValueParser`
  before it is emitted; a value the formatter cannot represent losslessly
  is written as raw hex (`0x...`) instead, so `generate |> parse` always
  reproduces the input bytes. Compound TLVs are split with the shared
  `Bindocsis.TlvLength` codec; a compound whose bytes do not form a valid
  sub-TLV sequence is written as hex too.

  ## Options

  - `:include_header` - file header comment (default: true)
  - `:include_comments` - `# description` comment above each top-level TLV
    (default: true)
  - `:indent_size` - spaces per nesting level (default: 4)
  - `:format_style` - `:standard` (blank line between top-level TLVs) or
    `:compact` (default: `:standard`)
  - `:file_type` - `:docsis` or `:mta`; auto-detected from
    `mta_specific: true` metadata when omitted
  """

  alias Bindocsis.{ConfigNames, TlvLength, ValueFormatter, ValueParser}

  @string_types [:string, :string_null]
  @binary_types [:binary, :hex_string, :asn1_der, :vendor, :marker, :compound, :service_flow]

  @doc """
  Generates config text from TLVs.

      iex> Bindocsis.Generators.ConfigGenerator.generate([%{type: 3, length: 1, value: <<1>>}],
      ...>   include_header: false, include_comments: false)
      {:ok, "NetworkAccessControl Enabled\\n"}
  """
  @spec generate([map()], keyword()) :: {:ok, String.t()} | {:error, String.t()}
  def generate(tlvs, opts \\ []) when is_list(tlvs) do
    with :ok <- validate_tlvs(tlvs) do
      file_type = Keyword.get(opts, :file_type) || detect_file_type(tlvs)
      style = Keyword.get(opts, :format_style, :standard)

      header =
        if Keyword.get(opts, :include_header, true),
          do: header_lines(file_type, Keyword.get(opts, :docsis_version, "3.1")),
          else: []

      body =
        tlvs
        |> Enum.map(&tlv_lines(&1, [], 0, file_type, opts))
        |> join_blocks(style)

      {:ok, Enum.join(header ++ body, "\n") <> "\n"}
    end
  rescue
    error -> {:error, "Config generation error: #{Exception.message(error)}"}
  end

  @doc "Writes generated config text to `path`."
  @spec write_file([map()], String.t(), keyword()) :: :ok | {:error, String.t()}
  def write_file(tlvs, path, opts \\ []) do
    with {:ok, content} <- generate(tlvs, opts),
         :ok <- File.write(path, content) do
      :ok
    else
      {:error, reason} when is_atom(reason) -> {:error, "File write error: #{reason}"}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc "Checks every TLV has a type in 0..255 and a value matching its length."
  @spec validate_tlvs([map()]) :: :ok | {:error, String.t()}
  def validate_tlvs(tlvs) when is_list(tlvs) do
    case Enum.find_index(tlvs, &invalid_tlv?/1) do
      nil -> :ok
      index -> {:error, "Invalid TLV at index #{index}"}
    end
  end

  @doc "Type -> identifier for the DOCSIS namespace (spec derived)."
  @spec supported_types() :: %{non_neg_integer() => String.t()}
  def supported_types, do: ConfigNames.docsis_names()

  # -- lines ------------------------------------------------------------------

  defp tlv_lines(%{type: type, value: value} = tlv, path, depth, ft, opts) do
    indent = String.duplicate(" ", depth * Keyword.get(opts, :indent_size, 4))
    name = ConfigNames.name(type, path, ft)

    comment =
      with true <- depth == 0 and Keyword.get(opts, :include_comments, true),
           desc when is_binary(desc) <- ConfigNames.description(type, path, ft) do
        ["#{indent}# #{desc}"]
      else
        _ -> []
      end

    body =
      if ConfigNames.compound?(type, path, ft) do
        case TlvLength.split(value) do
          {:ok, []} ->
            ["#{indent}#{name} { }"]

          {:ok, children} ->
            child_lines =
              Enum.flat_map(children, &tlv_lines(&1, path ++ [type], depth + 1, ft, opts))

            ["#{indent}#{name} {"] ++ child_lines ++ ["#{indent}}"]

          {:error, _} ->
            ["#{indent}#{name} #{hex_leaf(value)}"]
        end
      else
        ["#{indent}#{name} #{format_leaf(value, ConfigNames.value_type(type, path, ft))}"]
      end

    _ = tlv
    comment ++ body
  end

  defp join_blocks(blocks, :compact), do: List.flatten(blocks)

  defp join_blocks(blocks, _standard) do
    blocks
    |> Enum.intersperse([""])
    |> List.flatten()
  end

  defp header_lines(:mta, _version),
    do: ["# PacketCable MTA Configuration File", "# Generated by Bindocsis", ""]

  defp header_lines(_docsis, version),
    do: ["# DOCSIS Configuration File", "# Generated by Bindocsis (DOCSIS #{version})", ""]

  # -- leaf values ----------------------------------------------------------

  defp format_leaf(<<>>, _vt), do: ~s("")

  defp format_leaf(value, vt) do
    cond do
      string_type?(vt) -> format_string(value, vt)
      binary_type?(vt) -> spaced_hex(value)
      true -> format_typed(value, vt)
    end
  end

  defp format_string(value, vt) do
    with {:ok, text} <- ValueFormatter.format_value(base_type(vt), value, []),
         true <- printable?(text),
         {:ok, ^value} <- ValueParser.parse_value(base_type(vt), text, []) do
      quote_string(text)
    else
      _ -> hex_leaf(value)
    end
  end

  defp format_typed(value, vt) do
    with {:ok, text} when is_binary(text) <- ValueFormatter.format_value(vt, value, []),
         true <- printable?(text) and not String.contains?(text, "\n"),
         {:ok, ^value} <- ValueParser.parse_value(vt, text, []) do
      text
    else
      _ -> hex_leaf(value)
    end
  end

  # Raw bytes in the unambiguous 0x form (accepted for every value type)
  defp hex_leaf(value), do: "0x" <> Base.encode16(value)

  defp spaced_hex(value) do
    value
    |> Base.encode16()
    |> String.graphemes()
    |> Enum.chunk_every(2)
    |> Enum.map_join(" ", &Enum.join/1)
  end

  defp quote_string(text) do
    escaped = text |> String.replace("\\", "\\\\") |> String.replace("\"", "\\\"")
    ~s("#{escaped}")
  end

  defp printable?(text) do
    text |> :binary.bin_to_list() |> Enum.all?(&(&1 >= 32 and &1 <= 126))
  end

  defp string_type?({:enum, _, _}), do: false
  defp string_type?(vt), do: vt in @string_types
  defp binary_type?({:enum, _, _}), do: false
  defp binary_type?(vt), do: vt in @binary_types
  defp base_type({:enum, _, base}), do: base
  defp base_type(vt), do: vt

  # The MTA binary parser tags its TLVs; that is the only spec-backed signal
  # for PacketCable content (DOCSIS 3.x/4.0 also define TLVs 64-95).
  defp detect_file_type(tlvs) do
    if Enum.any?(tlvs, &(Map.get(&1, :mta_specific) == true)), do: :mta, else: :docsis
  end

  defp invalid_tlv?(%{type: type, length: length, value: value})
       when is_integer(type) and is_integer(length) and is_binary(value) do
    type < 0 or type > 255 or length < 0 or byte_size(value) != length
  end

  defp invalid_tlv?(_), do: true
end
